name=input("Enter the name:")
mobileno=int(input("Enter the number:"))
product_name1=input("Enter the product1:")
price1=float(input("Enter the price:"))
product_name2=input("Enter the product2:")
price2=float(input("Enter the price:"))
product_name3=input("Enter the product3:")
price3=float(input("Enter the price:"))
print(f"{name} your bill:")
print(f"{product_name1}:{price1}")
print(f"{product_name2}:{price2}")
print(f"{product_name3}:{price3}")
total_bill=price1+price2+price3
print(f"your bill is {total_bill}")